module.exports = {
  apps: [
    {
      name: 'aegis-trader-api',
      script: 'python',
      args: '-m src.api',
      cwd: '/app',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        AEGIS_ENVIRONMENT: 'production',
        AEGIS_LOG_LEVEL: 'INFO',
      },
      env_production: {
        NODE_ENV: 'production',
        AEGIS_ENVIRONMENT: 'production',
        AEGIS_LOG_LEVEL: 'INFO',
      },
      error_file: '/app/logs/err.log',
      out_file: '/app/logs/out.log',
      log_file: '/app/logs/combined.log',
      time: true,
    },
    {
      name: 'aegis-trader-scheduler',
      script: 'python',
      args: '-m src.scheduler',
      cwd: '/app',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        AEGIS_ENVIRONMENT: 'production',
        AEGIS_LOG_LEVEL: 'INFO',
      },
      env_production: {
        NODE_ENV: 'production',
        AEGIS_ENVIRONMENT: 'production',
        AEGIS_LOG_LEVEL: 'INFO',
      },
      error_file: '/app/logs/scheduler-err.log',
      out_file: '/app/logs/scheduler-out.log',
      log_file: '/app/logs/scheduler-combined.log',
      time: true,
    },
    {
      name: 'aegis-trader-web',
      script: 'npm',
      args: 'start',
      cwd: '/app/web',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        NEXT_PUBLIC_API_URL: 'http://localhost:8000',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
        NEXT_PUBLIC_API_URL: 'http://localhost:8000',
      },
      error_file: '/app/logs/web-err.log',
      out_file: '/app/logs/web-out.log',
      log_file: '/app/logs/web-combined.log',
      time: true,
    },
  ],

  deploy: {
    production: {
      user: 'ubuntu',
      host: '18.136.151.164',
      ref: 'origin/master',
      repo: 'https://github.com/Drizzlezhang/Aegis-Trader.git',
      path: '/home/ubuntu/aegis-trader',
      'post-deploy': 'npm install && npm run build && pm2 reload ecosystem.config.js --env production',
      env: {
        NODE_ENV: 'production',
        AEGIS_ENVIRONMENT: 'production',
      },
    },
  },
};