[supervisord]
nodaemon=true
user=root
logfile=/app/logs/supervisord.log
pidfile=/tmp/supervisord.pid

[program:backend]
command=uvicorn src.api.main:app --host 0.0.0.0 --port 8001
environment=PYTHONUNBUFFERED="1"
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/logs/backend.log
stderr_logfile=/app/logs/backend.log
priority=1
startretries=5

[program:frontend]
command=npm start
directory=/app/web
autostart=true
autorestart=true
stdout_logfile=/app/logs/frontend.log
stderr_logfile=/app/logs/frontend.log
priority=2
startsecs=5
startretries=5

[eventlistener:processes]
command=/bin/bash -c "printf 'READY\n' && while read line; do kill -SIGQUIT $PPID; done < /dev/stdin"
events=PROCESS_STATE_FATAL
